import type { Sneaker } from "./types"

export const sneakers: Sneaker[] = [
  {
    id: "1",
    name: "Air Max Revolution",
    brand: "Nike",
    price: 159.99,
    originalPrice: 189.99,
    images: ["/placeholder.svg?key=md25j", "/placeholder.svg?key=x292r", "/placeholder.svg?key=6i2s6"],
    description: "Révolutionnez votre style avec ces Air Max iconiques. Confort exceptionnel et design moderne.",
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Blanc/Noir", "Noir/Rouge", "Gris/Bleu"],
    category: "running",
    isNew: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "2",
    name: "Stan Smith Classic",
    brand: "Adidas",
    price: 89.99,
    images: ["/placeholder.svg?key=yeusf", "/placeholder.svg?key=7totx", "/placeholder.svg?key=vdpmi"],
    description: "L'intemporel Stan Smith. Un classique qui ne se démode jamais.",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    colors: ["Blanc/Vert", "Blanc/Marine", "Tout Blanc"],
    category: "lifestyle",
    isBestSeller: true,
    inStock: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: "3",
    name: "Jordan Retro High",
    brand: "Jordan",
    price: 199.99,
    images: ["/placeholder.svg?key=esgzc", "/placeholder.svg?key=e33yn", "/placeholder.svg?key=i1enc"],
    description: "L'héritage du basketball dans une silhouette iconique. Style et performance réunis.",
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45", "46"],
    colors: ["Rouge/Noir/Blanc", "Noir/Blanc", "Bleu Royal/Blanc"],
    category: "basketball",
    inStock: true,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "4",
    name: "Chuck Taylor All Star",
    brand: "Converse",
    price: 69.99,
    images: ["/placeholder.svg?key=qzzym", "/placeholder.svg?key=6nuzp", "/placeholder.svg?key=levpi"],
    description: "Le classique intemporel. Simplicité et authenticité depuis 1917.",
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    colors: ["Noir", "Blanc", "Rouge", "Marine"],
    category: "lifestyle",
    isBestSeller: true,
    inStock: true,
    rating: 4.4,
    reviewCount: 203,
  },
  {
    id: "5",
    name: "Yeezy Boost 350",
    brand: "Adidas",
    price: 249.99,
    images: ["/placeholder.svg?key=o6vk0", "/placeholder.svg?key=wxoru", "/placeholder.svg?key=rfn6w"],
    description: "Innovation et style futuriste. La technologie Boost pour un confort ultime.",
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Cream White", "Core Black", "Zebra"],
    category: "limited-edition",
    isNew: true,
    inStock: false,
    rating: 4.7,
    reviewCount: 78,
  },
  {
    id: "6",
    name: "Old Skool Pro",
    brand: "Vans",
    price: 79.99,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description: "L'authentique chaussure de skate. Durabilité et style street depuis 1977.",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Noir/Blanc", "Marine/Blanc", "Bordeaux/Blanc"],
    category: "skateboarding",
    inStock: true,
    rating: 4.5,
    reviewCount: 167,
  },
]

export const categories = [
  { id: "all", name: "Tous", count: sneakers.length },
  { id: "running", name: "Running", count: sneakers.filter((s) => s.category === "running").length },
  { id: "lifestyle", name: "Lifestyle", count: sneakers.filter((s) => s.category === "lifestyle").length },
  { id: "basketball", name: "Basketball", count: sneakers.filter((s) => s.category === "basketball").length },
  { id: "skateboarding", name: "Skateboarding", count: sneakers.filter((s) => s.category === "skateboarding").length },
  {
    id: "limited-edition",
    name: "Édition Limitée",
    count: sneakers.filter((s) => s.category === "limited-edition").length,
  },
]
